more largedata, srb client lib now seem ok

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE LN_S CPP EGREP LIBOBJS readlinelib MAJOR_VERSION MINOR_VERSION PATCH_VERSION LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE LN_S CPP EGREP LIBOBJS readlinelib PIE FPIE MAJOR_VERSION MINOR_VERSION PATCH_VERSION LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -847,6 +847,7 @@ Optional Features:
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-multicast          use multicast for srb query (default yes)
   --enable-broadcast          use broadcast for srb query (default yes)
+  --enable-pie          This enables position independent executables.
   --enable-timepegs          This enable the timepegs in the code, which log at INFO level the time spent thru the code.
 
 Some influential environment variables:
@@ -4597,6 +4598,82 @@ else
 fi
 
 
+echo "$as_me:$LINENO: checking for xmlParseFile in -lxml2" >&5
+echo $ECHO_N "checking for xmlParseFile in -lxml2... $ECHO_C" >&6
+if test "${ac_cv_lib_xml2_xmlParseFile+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lxml2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char xmlParseFile ();
+int
+main ()
+{
+xmlParseFile ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_xml2_xmlParseFile=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_xml2_xmlParseFile=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_xml2_xmlParseFile" >&5
+echo "${ECHO_T}$ac_cv_lib_xml2_xmlParseFile" >&6
+if test $ac_cv_lib_xml2_xmlParseFile = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBXML2 1
+_ACEOF
+
+  LIBS="-lxml2 $LIBS"
+
+else
+  echo "missing xml2 library"; exit;
+fi
+
+
 
 staticpre="-Wl,-Bstatic"
 staticpost="-Wl,-Bdynamic"
@@ -4651,18 +4728,35 @@ _ACEOF
      *)          echo 'parameter should be =yes or =no' ; exit 1 ;;
 esac
 
-enable_timepegs=no
-{ echo "$as_me:$LINENO: Timepegs enable = $enable_timepegs" >&5
-echo "$as_me: Timepegs enable = $enable_timepegs" >&6;}
 
+# Check whether --enable-pie or --disable-pie was given.
+if test "${enable_pie+set}" = set; then
+  enableval="$enable_pie"
+  enable_pie=$enableval
+else
+  enable_pie="no"
+fi;
+{ echo "$as_me:$LINENO: Pie enable = $enable_pie" >&5
+echo "$as_me: Pie enable = $enable_pie" >&6;}
+
+case "$enable_pie" in
+     no|NO)   enable_pie=no
+		 ;;
+     yes|YES)    enable_pie=yes
+		 PIE="-pie"
+
+		 FPIE="-fpie"
+
+		 ;;
+     *)          echo 'parameter should be =yes or =no' ; exit 1 ;;
+esac
+
+enable_timepegs=no
 # Check whether --enable-timepegs or --disable-timepegs was given.
 if test "${enable_timepegs+set}" = set; then
   enableval="$enable_timepegs"
 
 fi;
-
-{ echo "$as_me:$LINENO: Timepegs enable = $enable_timepegs" >&5
-echo "$as_me: Timepegs enable = $enable_timepegs" >&6;}
 
 case "$enable_timepegs" in
      no|NO|'')   enable_timepegs=no
@@ -4675,6 +4769,8 @@ _ACEOF
 		 ;;
      *)          echo 'parameter should be =yes or =no' ; exit 1 ;;
 esac
+{ echo "$as_me:$LINENO: Timepegs enable = $enable_timepegs" >&5
+echo "$as_me: Timepegs enable = $enable_timepegs" >&6;}
 
 
 
@@ -5345,6 +5441,8 @@ s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@readlinelib@,$readlinelib,;t t
+s,@PIE@,$PIE,;t t
+s,@FPIE@,$FPIE,;t t
 s,@MAJOR_VERSION@,$MAJOR_VERSION,;t t
 s,@MINOR_VERSION@,$MINOR_VERSION,;t t
 s,@PATCH_VERSION@,$PATCH_VERSION,;t t
